### ISSUE TITLE
Request for `.to.not.emit` matcher

### ISSUE THREAD

**Issue by j1mmie** [TrueFiEng/Waffle#532]
Based on other Chai matcher patterns, I expected `.to.not.emit` to work. However, it does not seem to be implemented, and  I have not found a way to ensure a particular event does not get emitted. I can test for other failure cases, but I could see a situation where a refactor causes an event to emit even when the call does not behave as expected. Having `.to.not.emit` would ensure that my code stays on the tracks. 

Example usage:

```
it('Should not emit a transfer event', async () => {
  await expect(token.transfer(walletTo.address, 0))
    .to.not.emit(token, 'Transfer')
})
```

Stretch goal would be to chain multiple conditions. This directly solves my concern, but may not be considered best practice for tests.
```
it('Should not emit a transfer event', async () => {
  await expect(token.transfer(walletTo.address, 0))
    .to.be.reverted()
    .and.not.emit(token, 'Transfer')
})
```

Would love to submit a PR for this, but wanted to get the ball rolling on a discussion first.

**Comment by yivlad** [comment]
It's already supported as shown [here] (https://github.com/TrueFiEng/Waffle/blob/ba7033f53b098e242c77ea9513f840e513bc1a72/waffle-chai/test/matchers/eventsTest.ts#L82-L84). Also testing for transaction to be reverted and not to emit events doesn't make much sense because reverted transactions do not emit any events. So chaining `reverted` and `revertedWith` matchers is unsupported as for now.
